# Generated by Django 2.0.5 on 2019-10-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191016_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pv',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='article',
            name='uv',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, '删除'), (1, '正常'), (0, '草稿')], default=1, verbose_name='状态'),
        ),
    ]
